#docker run -d --name dd-agent \
#-e DD_API_KEY=<api-key> \
#-e DD_SITE="us5.datadoghq.com" \
#-e DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true \
#-v /var/run/docker.sock:/var/run/docker.sock:ro \
#-v /proc/:/host/proc/:ro \
#-v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
#-v /var/lib/docker/containers:/var/lib/docker/containers:ro \
#gcr.io/datadoghq/agent:7

#  docker compose up -d
version: "3.8"

services:
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    restart: unless-stopped

    environment:
      DD_API_KEY: <api-key>
      DD_SITE: us5.datadoghq.com
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./conf.yaml:/etc/datadog-agent/conf.d/openmetrics.d/conf.yaml:ro
